<?php

/**
 * Implementation of hook_menu().
 */
function ext_admin_menu()
{
  $items['admin/config/custom'] = array(
    'title' => 'Custom',
    'position' => 'right',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/custom/settings'] = array(
    'title' => 'Настройки',
    'weight' => 0,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ext_admin_settings_form'),
    'access arguments' => array('access manager settings'),
    'file' => 'includes/ext_admin.settings.inc',
  );
  $items['admin/config/custom/migration'] = array(
    'title' => 'Перенос данных',
    'weight' => 1,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ext_admin_migration_form'),
    'access arguments' => array('access manager settings'),
  );

  return $items;
}

/**
 * Implements hook_cron_queue_info().
 */
function ext_admin_cron_queue_info()
{
  $queues['ext_admin_queue_worker'] = array(
    'worker callback' => 'ext_admin_queue_callback',
  );

  return $queues;
}

function ext_admin_migration_form($form, &$form_state)
{
  $function = '';
  $function = 'ext_admin_process_migration';

  $form['message'] = array(
    '#markup' => ($function ? '<p>Будет запущена функция ' . $function . '</p>' : '<p>Функция для запуска не задана</p>'),
  );
  $form['control'] = array(
    '#type' => 'checkbox',
    '#title' => 'контрольная галка',
    '#description' => 'установить перед запуском',
    '#default_value' => false,
  );
  $form['function'] = array(
    '#type' => 'hidden',
    '#value' => $function,
  );
  $form['run'] = [
    '#type' => 'submit',
    '#value' => 'Пуск!',
  ];

  return $form;
}
function ext_admin_migration_form_validate($form, &$form_state)
{
  if (!$form_state['values']['function']) {
    form_set_error('','Нужно задать функцию, которая будет запущена');
    return false;
  }
  if (!function_exists($form_state['values']['function'])) {
    form_set_error('', 'Заданная функция ' . $form_state['values']['function'] . ' не существует');
    return false;
  }
  if (!$form_state['values']['control']) {
    form_set_error('control', 'Нужно установить контроль');
    return false;
  }
}
function ext_admin_migration_form_submit($form, &$form_state)
{
  $function = $form_state['values']['function'];
  if ($function()) {
    drupal_set_message('Запуск выполнен успешно');
  } else {
    drupal_set_message('Неуспешный пуск', 'warning');
  }
}

function ext_admin_process_migration()
{
  $queue = DrupalQueue::get('ext_admin_queue_worker');
  $queue->deleteQueue();
  return;
  // список для очереди пока только за 2025
  for ($i=1; $i<=12; $i++) {
    $counter = 0;
    $month_start = gmmktime(0, 0, 0, $i, 1, 2024);

    prod_message_delete_all($month_start);
    prod_plan_record_delete_all($month_start);

    // получить список номенклатуры
    $dbr = db_select('field_data_field_nomenklatura', 'fn');
    $dbr->condition('fn.entity_type', 'query');
    $dbr->innerJoin('field_data_field_month', 'fm', 'fm.entity_id = fn.entity_id');
    $dbr->condition('fm.field_month_value', $month_start);
    $dbr->distinct();
    $dbr->addField('fn', 'field_nomenklatura_target_id', 'tid');
    $nom_ids = $dbr->execute()->fetchCol();

    if ($nom_ids) {
      foreach ($nom_ids as $nom_id) {
        if (false && !in_array($nom_id, [
            3047,
  //        3977,
  //        200,
  //        362
        ])) continue; // пока только для одной номенклатуры

        $efQuery = new EntityFieldQuery();
        $efQueries = $efQuery
          ->entityCondition('entity_type', 'query')
          ->fieldCondition('field_month', 'value', $month_start)
          ->fieldCondition('field_nomenklatura', 'target_id', $nom_id)
          ->propertyOrderBy('id')
          ->execute();

        // сервисную заявку только последнюю
        $efQuery = new EntityFieldQuery();
        $efService = $efQuery
          ->entityCondition('entity_type', 'query')
          ->fieldCondition('field_month', 'value', $month_start)
          ->fieldCondition('field_query_type', 'value', 'service')
          ->propertyOrderBy('id', 'DESC')
          ->range(0, 1)
          ->execute();

        if ($efQueries) {
          foreach ($efQueries['query'] as $query) {
            $queue->createItem($query->id);
            $counter++;
          }
          if ($efService) $queue->createItem(reset($efService['query'])->id);
        }
      }

      drupal_set_message('Месяц: ' . $i . '. Элементов: ' . $counter);
    }
  }

  $dest = strpos($_SERVER["HTTP_REFERER"], $GLOBALS["base_url"]) !== false ? $_SERVER["HTTP_REFERER"] : false;
  if ($dest) {
    drupal_goto($dest);
  }
}

function ext_admin_queue_callback($qid)
{
  prod_query_migrate($qid);
}

