<?php

const MONTHS = [ 1 => 'Январь' , 'Февраль' , 'Март' , 'Апрель' , 'Май' , 'Июнь' , 'Июль' , 'Август' , 'Сентябрь' , 'Октябрь' , 'Ноябрь' , 'Декабрь' ];

/**
 * Вернуть название месяца на русском в именительном или родительном падеже
 * @param $month_index
 * @param $roditelniy
 */
function helper_month_label_ru($month_index, $roditelniy = false)
{
  $months = $roditelniy ? explode('|', 'января|февраля|марта|апреля|мая|июня|июля|августа|сентября|октября|ноября|декабря') : explode('|', 'Январь|Февраль|Март|Апрель|Май|Июнь|Июль|Август|Сентябрь|Октябрь|Ноябрь|Декабрь');

  return $months[$month_index-1];
}

/**
 * Вернуть отформатированное число
 */
function helper_number_format($number, $decimals, $thousands_separator = '', $trailing_cut = true)
{
  // форматируем согласно заданному количеству знаков после запятой
  $result = number_format($number, $decimals, ',', $thousands_separator);
  // обрезаем ноли после запятой
  if ($trailing_cut) {
    $result = str_replace(',' . str_pad('', $decimals, '0'), '', $result);
    $result = strpos($result, ',') ? rtrim($result, '0') : $result;
  }

  return $result;
}

/**
 * Преобразовать текстовую дату или дату и время в unix
 *
 * @param $datetime - в формате d.m.Y H:i
 * @return - unix timestamp
 */
function helper_datetime_to_timestamp($datetime)
{
  $timestamp = 0;
  $datetime_arr = explode(' ', $datetime);

  if ($datetime_arr[0]) {
    $date_arr = explode('.', $datetime_arr[0]);
    $hours = $minutes = 0;
    if (!empty($datetime_arr[1])) {
      $time_arr = explode(':', $datetime_arr[1]);
      $hours = $time_arr[0];
      $minutes = $time_arr[1];
    }

    $timestamp = gmmktime($hours, $minutes, 0, $date_arr[1], $date_arr[0], $date_arr[2]);
  }

  return $timestamp;
}

/**
 * Вернуть timestamp начала заданного дня
 * @param $timestamp
 * @return false|int - unix timastamp
 */
function helper_get_day_start_from_timestamp($timestamp = REQUEST_TIME)
{
  return gmmktime(0, 0, 0, date('n', $timestamp), date('j', $timestamp) , date('Y', $timestamp));
}

/**
 * Вернуть timestamp начала месяца
 * @param $timestamp
 * @return false|int - unix timastamp
 */
function helper_get_month_start_from_timestamp($timestamp = REQUEST_TIME)
{
  return gmmktime(0, 0, 0, date('n', $timestamp), 1 , date('Y', $timestamp));
}

/**
 * Вернуть массив информации о термине таксономии
 */
function helper_get_term_info($term)
{
  $term_info = &drupal_static(__FUNCTION__ . serialize($term));
  if (!isset($term_info)) {
    $term_info = [];
    $term_wr = entity_metadata_wrapper('taxonomy_term', $term);
    if ($term_wr->value()) {
      $voc = taxonomy_vocabulary_load($term_wr->value()->vid);
      $term_info = [
        'id' => $term_wr->getIdentifier(),
        'label' => $term_wr->label(),
        'description' => $term_wr->description->value(),
        'weight' => $term_wr->weight->value(),
        'voc' => [
          'id' => $voc->vid,
          'name' => $voc->machine_name,
        ],
        'path' => url('taxonomy/term/' . $term_wr->getIdentifier()),
      ];

      // todo по списку полей добавить значения в массив
      if ($fields = field_info_instances('taxonomy_term', $voc->machine_name)) {
        foreach ($fields as $name => $field) {
          if (!in_array($name, ['name_field', 'description_field'])) {
            $term_info[$name] = $term_wr->{$name}->value();
          }
        }
      }
    }
  }

  return $term_info;
}
